// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_split_pdf
Rcpp::CharacterVector cpp_split_pdf(char const* infile, std::string outprefix);
RcppExport SEXP _qpdf_cpp_split_pdf(SEXP infileSEXP, SEXP outprefixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< char const* >::type infile(infileSEXP);
    Rcpp::traits::input_parameter< std::string >::type outprefix(outprefixSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_split_pdf(infile, outprefix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qpdf_cpp_split_pdf", (DL_FUNC) &_qpdf_cpp_split_pdf, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_qpdf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
