# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pdf_length <- function(infile) {
    .Call('_qpdf_cpp_pdf_length', PACKAGE = 'qpdf', infile)
}

cpp_pdf_split <- function(infile, outprefix) {
    .Call('_qpdf_cpp_pdf_split', PACKAGE = 'qpdf', infile, outprefix)
}

cpp_pdf_select <- function(infile, outfile, which) {
    .Call('_qpdf_cpp_pdf_select', PACKAGE = 'qpdf', infile, outfile, which)
}

cpp_pdf_combine <- function(infiles, outfile) {
    .Call('_qpdf_cpp_pdf_combine', PACKAGE = 'qpdf', infiles, outfile)
}

cpp_pdf_compress <- function(infile, outfile) {
    .Call('_qpdf_cpp_pdf_compress', PACKAGE = 'qpdf', infile, outfile)
}

