# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_split_pdf <- function(infile, outprefix) {
    invisible(.Call('_qpdf_cpp_split_pdf', PACKAGE = 'qpdf', infile, outprefix))
}

